// Package ginsimple GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package ginsimple

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/book": {
            "put": {
                "description": "update the book into books list.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "update the book.",
                "parameters": [
                    {
                        "description": "bookEntity.GoBook data.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bookEntity.GoBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bookEntity.GoBook"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new book into gobooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "create book.",
                "parameters": [
                    {
                        "description": "bookEntity.GoBook data.",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bookEntity.GoBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bookEntity.GoBook"
                        }
                    }
                }
            }
        },
        "/book/{id}": {
            "delete": {
                "description": "delete the book from gobooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "delete the book from gobooks.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bookEntity.GoBook ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "read the books list.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "get the books list.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bookEntity.GoBook"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bookEntity.GoBook": {
            "type": "object",
            "required": [
                "author",
                "callnumber",
                "id",
                "publisher"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "callnumber": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:6060",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Books Sample Go Application",
	Description:      "This is a sample Books server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
