##
## Build
##
FROM golang:1.16-alpine3.13 AS builder

WORKDIR /app

COPY . .
RUN go mod download
RUN go build -o main main.go

##
## Run
##
FROM alpine:3.13
WORKDIR /app
COPY --from=builder /app/main .


EXPOSE 6060

CMD ["/app/main"]